
GET http://localhost:3001/todos/?status=TO%20DO 

### 
GET http://localhost:3001/todos/1/ 

### 
GET http://localhost:3001/agenda/?date=2021-14-12 

### 
POST http://localhost:3001/todos/ 
Content-Type: application/json 

{
 "id": 11,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-12-53"
}

### 
PUT http://localhost:3001/todos/1/ 
Content-Type: application/json 

{ "dueDate": "2021-03-16" }

### 
DELETE http://localhost:3001/todos/8/

